### ISSUE TITLE
Endpoint output encoding resets to JSON

### ISSUE THREAD

**Issue by emilrowland** [devopsfaith/krakendesigner#76] opened 2020-05-17 18:10 UTC
Every time I leave an endpoint with an other output encoidng then JSON, it resets back to JSON and clear my backend.

**Comment by alombarte** [comment] 2020-05-18 08:06
Thanks @emilrowland 

Can you describe the steps to reproduce this behavior?

**Comment by lodgify-daniel** [comment] 2020-07-01 07:41
Hello @alombarte 

This is happening to me also, in Service Configuration, with _Encoding_ and _Backend Timeout_.

I change to different values, I save to a new `krakend.json` file, since here everything works fine.
But if I try to load again the file into the Designer, even in the preview those values looks correct then are set as default again in their fields, so after save it again the values are wrong.

![image](https://user-images.githubusercontent.com/43340258/86216692-bda1ea80-bb7e-11ea-8a79-92c3e79a882c.png)
![image](https://user-images.githubusercontent.com/43340258/86216763-d6120500-bb7e-11ea-90d9-8c373d54d21b.png)

Hope you can fix soon, it's really annoying while I'm using the Designer as I need to set more timeout as the default.

Thanks

**Comment by alombarte** [comment] 2020-07-02 07:26
Thank you @lodgify-daniel for the detailed comment, thanks to this I was able to quickly identify the bug.

The problem should be fixed now. Let us know if you find any other issues.

**Closed by alombarte** 2020-07-02 07:26 UTC
